version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - app_logs:/home/app/server/logs
    environment:
      - PRODUCTION=true
    privileged: true
    security_opt:
      - seccomp:unconfined
    cgroup: host
    platform: linux/amd64
    user: app

volumes:
  app_logs: